### ISSUE TITLE
wget leaves Zombie processes on host system

### ISSUE THREAD

**Issue by lukaslindnermusic** [alangrainger/immich-public-proxy#66]
Hi 😊 

Since installing immich-public-proxy on my server, I noticed that every once in a while, there are zombie processes.
I previously never had zombie processes on my system, so I checked what is causing the processes.

The processes are the wget cmd, apparently executed by `dist/index.js`, caused by pm2-runtime which is started by the docker container of immich-public-proxy.
I don't know, what exactly is causing the zombie processes, but here is an excerpt of my docker container log with the PM2 messages:
```
2025-02-08T00:12:38: PM2 log: Stopping app:index id:0
2025-02-08T00:12:38: PM2 error: Error: spawn ps ENOENT
2025-02-08T00:12:39: PM2 log: App [index:0] exited with code [0] via signal [SIGINT]
2025-02-08T00:12:39: PM2 log: pid=18 msg=process killed
2025-02-08T00:12:39: PM2 log: PM2 successfully stopped
2025-02-08T00:13:14: PM2 log: Launching in no daemon mode
2025-02-08T00:13:14: PM2 log: App [index:0] starting in -fork mode-
2025-02-08T00:13:14: PM2 log: App [index:0] online
```
Is this caused by something in the immich-public-proxy code or is it a bug in dependencies? 

Thanks for your help 😊

**Comment by alangrainger** [comment]
Thanks for the info - I was thinking of removing PM2 anyway, as I'm not convinced it does anything useful. That should solve the issue after I do that.

**Comment by alangrainger** [comment]
PM2 is now removed :)

**Comment by AlphaCraft9658** [comment]
I need to notify you about the fact that Immich-Public-Proxy still appears to be spawning wget zombie processes. They might be related to some instabilities of my server that I have noticed recently, tho I am not sure whether it sort of leaks RAM and takes it down. Either way, Immich-Public-Proxy is still spawning those zombie processes on my system.

**Comment by alangrainger** [comment]
@AlphaCraft9658 it looks like the version of wget included with Alpine is a very old or cut-down version.

Can you update to the latest IPP, and try updating your docker-compose healthcheck line to this:

`test: wget -q -T 10 --spider http://localhost:3000/share/healthcheck || exit 1`

See if that gets any better result. If not, I might have to install curl as part of the build and use that.

**Comment by AlphaCraft9658** [comment]
> [@AlphaCraft9658](https://github.com/AlphaCraft9658) it looks like the version of wget included with Alpine is a very old or cut-down version.
> 
> Can you update to the latest IPP, and try updating your docker-compose healthcheck line to this:
> 
> `test: wget -q -T 10 --spider http://localhost:3000/share/healthcheck || exit 1`
> 
> See if that gets any better result. If not, I might have to install curl as part of the build and use that.

I updated and changed the health check, but it still spawns zombie processes eventually.

**Comment by alangrainger** [comment]
I have replaced wget with curl in 1.11.0 - see if that resolves things.

**Comment by alangrainger** [comment]
I'm closing this for now as I can see no zombie processes are created on my server, however they _are_ created for Caddy, which uses wget from Alpine.

So I think that was indeed the issue.

Feel free to reply and I can re-open if not resolved for you.
