### ISSUE TITLE
Download fails with large files

### ISSUE THREAD

**Issue by petarpetkov** [alangrainger/immich-public-proxy#94]
Attempting to download a file that is 60gb results in a container restart.
The only relevant information inside the container log is this:
```
immich-public-proxy  | 2025-05-13T16:33:20+00:00 Serving link <redacted>
immich-public-proxy exited with code 0
immich-public-proxy  | 2025-05-13T16:35:25+00:00 Server started on port 3000
```
The container is behind a cloudflare tunnel but attempting a direct connection to the container via {local-network-ip}/share fails the same way.

For me the container is hosted inside truenas scale 25.04 using dockge for ease.

**Comment by upmcplanetracker** [comment]
This is a random thought but I've had very large uploads directly to immich fail due to MTU size with cloudflare. I had to change mtu from 1500 to 1400 


Is this the same but the other direction?  I'm pretty sure the tunnels are not bidirectional and it happens without a tunnel but may be worth a try.

**Comment by pauldovi** [comment]
Possible this - https://github.com/alangrainger/immich-public-proxy/issues/288

**Comment by alangrainger** [comment]
This should be fixed in v3.3.0. Single-asset downloads now honour backpressure (#288) and "download all" streams the zip without staging to disk (#289), so a 60 GB file no longer blows up the container. Please reopen if you still see it.

**Comment by mFIND** [comment]
@alangrainger 
I think this is still somewhat broken.
I'm able to use "Download all" to download quite large archives. This works probably thanks to streaming.
Save-as I believe already streamed, so this is not a problem?

Problem is, when there is a single asset with size over ~200MB (not sure what is the limit there), when I try to download such singular asset via top download button, this still breaks.


EDIT:
I think it would be good to stream singular file downloads as well (potentially, only, when IPP detects, that the file to be downloaded is _large_

**Comment by alangrainger** [comment]
Thanks - you are right. Downloading an individual 1GB asset from the lightbox works, but from the gallery page it doesn't. Although I think a second problem there is that a single asset shouldn't be inside a zip as the zip is pointless in that circumstance.

Will get it sorted.

**Comment by alangrainger** [comment]
@mFIND it looks like an issue with how Cloudflare handles that stream. I have released 3.3.1 which adds a `no-store` cache control header to the download path.

If you happen to have a "Cache everything" rule that doesn't respect the origin headers, then you can add a bypass cache rule for `/share/*/download` and `/s/*/download` paths.

**Comment by mFIND** [comment]
@alangrainger not the case for me, I don't have cloudflare, downloading straight from my server over local network.
Still a problem on 3.3.1. Should I open separate issue to not clog this one?

**Comment by alangrainger** [comment]
Uh oh. I can't get it to fail on LAN straight from the server. 

1. Do you see anything in the IPP logs when the download fails?
2. When you say top button, do you mean in the lightbox or on a single item gallery page?
3. Do you have a reverse proxy in front of IPP? Which one?

**Comment by mFIND** [comment]
1. IPP logs do not show anything. immich DEBUG logs.. show about 8 requests to (..)/playback?key=(..) endpoint. Its 1-2 requests when the target (transcoded video) file is relatively small (48MB vs 273MB). The issue seems to be only with larger files
2. I believe this is lightbox; clicking IPP link shows a gallery, afterwards clicked on a single item. The button is in the top right. Sharing config file as well:
```json
{
  "ipp": {
    "maxDownloadQuality": "fullsize",
    "allowDownload": 2,
    "showHomePage": false,
    "showMetadata": {
      "description": {
        "caption": false,
        "sidebar": true
      },
      "exif": {
        "enabled": true,
        "dateTimeOriginal": true
      },
      "location": {
        "enabled": true,
        "gps": true
      }
    }
  }
}
```
3. Yes, traefik. The issue persists with middlewares (and, by itself, traefik allows large file to be downloaded, even a couple of GB, likely not an issue).

**Comment by alangrainger** [comment]
I've changed two things which I hope should fix it:

- Downloads are now streamed straight through from Immich with backpressure, so a large file is never held in memory in the container. This is possibly the cause of the restart you saw.
- The download response now sends `X-Accel-Buffering: no`, so a reverse proxy in front of IPP will not try to buffer the whole file before sending it either.

Both are in v3.4.0. If you're on Cloudflare with a "cache everything" rule, also add a Bypass Cache rule for `/share/*/download` and `/s/*/download`. See https://docs.ipp.nz/troubleshooting

Please give it a try and let me know if it works.

**Comment by mFIND** [comment]
Uh.. hmm to check that, I first wanted to recreate the issue on 3.3.1, before upgrading.. guess what - I wasn't able to.. I'm not sure what traefik version I was running at the time, but tested current + previous two and .. yeah

but, from a good side, I also wasn't able to reproduce it on 3.4.0 .... :')
Tested on IPP 3.4.0 via traefik 3.7.13

So it was either my computer problems (win10, seldomly restarted, so might've run out of memory), or browser (I probably updated chrome before then and now)

As a side note.. you might want to change description of the last release. See accidental hyperlink pointing to non-existent domain
